language: android
android:
  components:
    # Use the latest platform tools
    - platform-tools
    - tools

    # Use the desired build tools
    - build-tools-23.0.1

    # Project target SDK
    - android-23

    # Project extra configuration
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew assemble lint